### PR TITLE
Recreation of GRPC publisher/subscribers

### LINKED ISSUE #120: Kafka Connect: Sink connector eventually gets stuck in retry loop
I'm running this pubsub connector from `master` as of opening this ticket, within a docker container based on `confluentinc/cp-kafka-connect:3.3.0-1`, which features kafka 0.11.0

Eventually, while piping messages from kafka to pubsub, the task will run into an HTTP/2 error and never be able to recover, repeating the error message below. This results in an increasing backlog, and a constantly repeated batch of messages.

The only thing that comes to mind with this is some sort of network address cache, causing the task to try and connect to a pubsub node which has been shut down. I found that the java included in the confluent container does not define a value for java's `networkaddress.cache.ttl` setting, so it defaults to forever. I then changed the value to 30 seconds (by forking the container to change the file itself) and restarted my workers, but the problem came back after a few hours.

```
# java -version
openjdk version "1.8.0_144"
OpenJDK Runtime Environment (Zulu 8.23.0.3-linux64) (build 1.8.0_144-b01)
OpenJDK 64-Bit Server VM (Zulu 8.23.0.3-linux64) (build 25.144-b01, mixed mode)
```

```
[2017-09-13 05:17:57,552] WARN Commit of WorkerSinkTask{id=athena-staging-pubsub-1} offsets timed out (org.apache.kafka.connect.runtime.WorkerSinkTask)
[2017-09-13 05:17:57,839] ERROR Commit of WorkerSinkTask{id=athena-staging-pubsub-1} offsets threw an unexpected exception: (org.apache.kafka.connect.runtime.WorkerSinkTask)
org.apache.kafka.clients.consumer.RetriableCommitFailedException: Offset commit failed with a retriable exception. You should retry committing offsets. The underlying error was: The request timed out.
[2017-09-13 06:47:52,831] ERROR WorkerSinkTask{id=athena-staging-pubsub-1} Offset commit failed, rewinding to last committed offsets (org.apache.kafka.connect.runtime.WorkerSinkTask)
java.lang.RuntimeException: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNAVAILABLE: HTTP/2 error code: NO_ERROR
Received Goaway
session_timed_out
at com.google.pubsub.kafka.sink.CloudPubSubSinkTask.flush(CloudPubSubSinkTask.java:293)
at org.apache.kafka.connect.sink.SinkTask.preCommit(SinkTask.java:117)
at org.apache.kafka.connect.runtime.WorkerSinkTask.commitOffsets(WorkerSinkTask.java:305)
at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:164)
at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:148)
at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:146)
at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:190)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNAVAILABLE: HTTP/2 error code: NO_ERROR
Received Goaway
session_timed_out
at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:500)
at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:459)
at com.google.pubsub.kafka.sink.CloudPubSubSinkTask.flush(CloudPubSubSinkTask.java:290)
... 11 more
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: HTTP/2 error code: NO_ERROR
Received Goaway
session_timed_out
at io.grpc.Status.asRuntimeException(Status.java:545)
at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:417)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:458)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$500(ClientCallImpl.java:385)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$3.runInContext(ClientCallImpl.java:486)
at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
... 3 more
```

### PR DESCRIPTION
**Pull request by kamalaboulhosn**
Periodically recreate GRPC publishers and subscribers in order to avoid GOAWAY errors. Hopefully fixes #120.

### CODE REVIEW

File: kafka-connector/src/main/java/com/google/pubsub/kafka/sink/CloudPubSubGRPCPublisher.java [hunk 1]
```diff
@@ -56,7 +56,8 @@ private void makePublisher() {
       log.info("Creating publisher.");
       publisher = PublisherGrpc.newFutureStub(ConnectorUtils.getChannel());
       // We change the publisher every 25 - 35 minutes in order to avoid GOAWAY errors.
-      nextPublisherResetTime = System.currentTimeMillis() + rand.nextInt(10 * 60 * 1000) + 25 * 60 * 1000;
+      nextPublisherResetTime =
```
Comment (mdietz94) [inline kafka-connector/src/main/java/com/google/pubsub/kafka/sink/CloudPubSubGRPCPublisher.java]: Is there no way to check on the channel itself, like by calling  isTerminated?

Comment (kamalaboulhosn) [reply kafka-connector/src/main/java/com/google/pubsub/kafka/sink/CloudPubSubGRPCPublisher.java]: It's a possibility we might be able to do that in the future. A second change will have to be made to not throw exceptions in the CloudPubSubSinkTask when flushing messages. When an exception is thrown, everything shuts down. That means introducing retry and making some significant changes to the class. Once we have that, then we can throw an exception when we have an error, detect when termination occurs, and recreate the publisher.

There is some urgency for a fix to this problem for a customer and so my hope was to use this to solve the problem in the meantime.

**Comment by kamalaboulhosn** [comment]
I switch to the client library in the sink connector. I'm going to leave things as-is in the source connector for now as the client library doesn't really make as much sense there. The sink connector is the more critical one right now.

PTAL?

File: kafka-connector/src/main/java/com/google/pubsub/kafka/sink/CloudPubSubSinkTask.java [hunk 2]
```diff
@@ -290,20 +250,19 @@ public void flush(Map<TopicPartition, OffsetAndMetadata> partitionOffsets) {
         continue;
       }
       try {
-        for (ListenableFuture<PublishResponse> publishFuture : outstandingFutures.futures) {
-          publishFuture.get();
-        }
+        ApiFutures.allAsList(outstandingFutures.futures).get();
+        // for (ApiFuture<String> publishFuture : outstandingFutures.futures) {
```
Comment (mdietz94) [inline kafka-connector/src/main/java/com/google/pubsub/kafka/sink/CloudPubSubSinkTask.java]: Remove this comment?

File: kafka-connector/src/main/java/com/google/pubsub/kafka/sink/CloudPubSubSinkTask.java [hunk 3]
```diff
@@ -317,20 +276,24 @@ private void publishMessagesForPartition(
...
-    // Publish all the messages for this partition in batches.
-    while (startIndex < messages.size()) {
-      PublishRequest request =
-          builder.setTopic(cpsTopic).addAllMessages(messages.subList(startIndex, endIndex)).build();
-      builder.clear();
-      log.trace("Publishing: " + (endIndex - startIndex) + " messages");
-      outstandingFutures.futures.add(publisher.publish(request));
-      startIndex = endIndex;
-      endIndex = Math.min(endIndex + CPS_MAX_MESSAGES_PER_REQUEST, messages.size());
+    outstandingFutures.futures.add(publisher.publish(message));
```
Comment (mdietz94) [inline kafka-connector/src/main/java/com/google/pubsub/kafka/sink/CloudPubSubSinkTask.java]: Unless this topic must always match the topic created by the publisher, I think you may need to have the publishers be Map<String,Publisher> since we don't support multiple topics in the same publisher by default right now.

Comment (kamalaboulhosn) [reply kafka-connector/src/main/java/com/google/pubsub/kafka/sink/CloudPubSubSinkTask.java]: The CPS topic is statically set in the config of the connector and used across all Kafka topics from which messages are received, so there is only a single topic to which we publish.

File: kafka-connector/src/main/java/com/google/pubsub/kafka/sink/CloudPubSubSinkTask.java (hunk 2 above)
Comment (kamalaboulhosn) [reply kafka-connector/src/main/java/com/google/pubsub/kafka/sink/CloudPubSubSinkTask.java]: Done.

File: kafka-connector/src/main/java/com/google/pubsub/kafka/sink/CloudPubSubSinkTask.java (hunk 3 above)
Comment (mdietz94) [reply kafka-connector/src/main/java/com/google/pubsub/kafka/sink/CloudPubSubSinkTask.java]: Should we remove topic from being a parameter to this function then?

Comment (kamalaboulhosn) [reply kafka-connector/src/main/java/com/google/pubsub/kafka/sink/CloudPubSubSinkTask.java]: No, topic refers to the _Kafka_ topic. The flush method is called for a specific Kafka topic and partition. When this method is called, we need to ensure that all messages for that specific Kafka topic and partition have successfully been published. This is why we track futures by topic and partition. The topic argument is not related to the CPS topic at all.
